baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Aki's Blog"
theme = 'paco'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    style = "monokai" # This will be overridden by our CSS classes
