baseURL = 'https://AkikoAkaki.github.io/aki-liu/'
languageCode = 'en-us'
title = "Aki's Blog"
theme = 'paco'
mainSections = ['writing']

[permalinks]
  writing = '/writing/:slug/'

[taxonomies]
  tag = 'tags'
  category = 'categories'

[params]
  enableKaTeX = true

  [params.navigation]
    homeLabel = 'Index'
    writingLabel = 'Writing'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardLineBreak = true
  [markup.highlight]
    noClasses = false
    style = "monokai" # This will be overridden by our CSS classes
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1
